% MATLAB Editor Run Commands
% @version 3
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name hh1
%  @associatedFile G:\360_Han\金山快盘\GuYong\Matlab\Neural Network MIT\HH model\hh1.m
%  @mostRecentlyActioned true
%  @uniqueId 1b70eca2:142ff0fe8a2:-7fcc

hh1(vstart0, tmax0, iappl0, istart0, istop0)

%% @name hop
%  @associatedFile F:\360_Han\金山快盘\GuYong\Matlab\Neural Network MIT\9_Hopfield\hop.m
%  @mostRecentlyActioned true
%  @uniqueId -44cd25c1:14907bd49c3:-7f50

hop

%% @name createFit
%  @associatedFile Z:\Data\MOOG\Results\createFit.m
%  @mostRecentlyActioned true
%  @uniqueId -d68273c:14955117612:-7f19

createFit(2,5)

