function fig = BATCH_GUI()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

clear all; close all; clc;
load BATCH_GUI

global LOAD_MU_DATA;
LOAD_MU_DATA = 0;

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','H:\Matlab\TEMPO_Analysis\BATCH_GUI.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[409 200 821 498], ...
	'Tag','Fig2', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0.501960784313725 0.501960784313725], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 300 125.25 13.5], ...
	'String','Data File Name:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0.501960784313725 0.501960784313725], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[16.5 345 61.5 12.75], ...
	'String','Data Path:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[9 224.25 187.5 138.75], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'ListboxTop',0, ...
	'Position',[204.75 225 266.25 138.75], ...
	'Style','frame', ...
	'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 1], ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[12.75 343.5 45 15], ...
	'String','Data Path:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[12.75 327.75 145.5 15], ...
	'String','Z:\data\tempo\batch files\', ...
	'Style','edit', ...
	'Tag','Pathname', ...
	'UserData','[ ]');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 1], ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[12.75 303.75 65.25 15], ...
	'String','Batch File Name:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 0.501960784313725], ...
	'Callback','BATCH_GUI_Switchyard(''file open'');', ...
	'ListboxTop',0, ...
	'Position',[136.5 282.75 54 29.25], ...
	'String','Browse', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'ForegroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[274.5 338.25 36 15], ...
	'String','Protocol:', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[274.5 282.75 174.75 15], ...
	'String',' ', ...
	'Style','popupmenu', ...
	'Tag','AnalysisList', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','BATCH_GUI_Switchyard(''filter on'')', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[210.75 339.75 51.75 15], ...
	'String','Filter ON', ...
	'Style','radiobutton', ...
	'Tag','FilterOn');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','BATCH_GUI_Switchyard(''filter off'')', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[210.75 324 53.25 15], ...
	'String','Filter OFF', ...
	'Style','radiobutton', ...
	'Tag','FilterOff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.501960784313725 1 0], ...
	'Callback','BATCH_GUI_Switchyard(''load data'')', ...
	'ListboxTop',0, ...
	'Position',[380.25 238.5 79.5 36], ...
	'String','Go Speed Racer GO!', ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 0], ...
	'Callback','Batch_gui_switchyard(''file info'')', ...
	'FontSize',20, ...
	'ListboxTop',0, ...
	'Position',[18.75 232.5 166.5 44.25], ...
	'String','Get Info', ...
	'Tag','InfoButton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 291.75 119.25 15], ...
	'Style','edit', ...
	'Tag','Filename');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Courier', ...
	'Position',[11.25 28.5 585.75 185.25], ...
	'String',' ', ...
	'Style','listbox', ...
	'Tag','MessageBox', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','BATCH_GUI_Switchyard(''change protocol'')', ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[307.5 340.5 132.75 15], ...
	'String','Direction Tuning', ...
	'Style','popupmenu', ...
	'Tag','ProtocolList', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[309.75 257.25 66 15], ...
	'String','Close Figures', ...
	'Style','checkbox', ...
	'Tag','CloseBox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Callback','BATCH_GUI_Switchyard(''load_mu_data_checkbox'')', ...
	'Position',[215.75 257.25 87 15], ...
	'String','Load Multi-Unit Data', ...
	'Style','checkbox', ...
	'Tag','LoadMUDataCheckBox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[309.75 242.25 63 15], ...
	'String','Print Figures', ...
	'Style','checkbox', ...
	'Tag','PrintBox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','BATCH_GUI_Switchyard(''override analysis'')', ...
	'Enable','off', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[274.5 299.25 170.25 15], ...
	'String','Override Preset Analysis with the following:', ...
	'Style','checkbox', ...
	'Tag','AnalysisBox');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 0 0], ...
	'ForegroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[274.5 324 33.75 13.5], ...
	'String','Rig:', ...
	'Style','text', ...
	'Tag','Static Text6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[307.5 324 80 15], ...
	'String',{'Moog 1','Moog 2','Moog 3','Mini Moog'}, ...
	'Style','popupmenu', ...
	'Tag','RigPopup', ...
	'Value',1);

if nargout > 0, fig = h0; end
